repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args:
        - --maxkb=100
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
    -   id: gitleaks
        args:
        - --staged
        - --verbose
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black, --line-length=120]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language_version: python3.12
        args: [--line-length=120]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        # Fix issues but skip import-sorting rules (I) to avoid conflicts with isort
        args: [--fix, --ignore=I]
